site_name: Apuntes
site_description: >
  Apuntes
site_dir: _site
site_url: "https://pamoreno.github.io/apuntes"
copyright: "Licencia: CC-BY-SA 4.0"

theme:
  name: material
  language: es
  features:
    - content.code.annotate
    - navigation.indexes
#    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - toc.follow
  palette:
    primary: teal
    accent: deep purple
  font:
    text: Roboto
    code: Fira Code

extra_javascript:
  - javascripts/mathjax.js
  - javascripts/fontawesome/all.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - css/bootstrap-card.css
  - css/cards.css
  - css/extra.css
  - css/fontawesome/all.min.css
  - css/quotes.css

plugins:
  - git-authors
  - git-revision-date-localized
  - glightbox
  - macros

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - codehilite:
      guess_lang: false
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - meta
  - toc:
      permalink: "#"
      toc_depth: 3
      slugify: !!python/name:pymdownx.slugs.uslugify
  - smarty
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shortener: true
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
      base_path: ['docs', 'docs/apuntes-c']
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Programación en C:
    - Compilando con el GCC: apuntes-c/compilando.md
    - Arreglos: apuntes-c/arreglos.md
    - Cadenas: apuntes-c/cadenas.md
    - Punteros: apuntes-c/punteros.md
    - Argumentos en línea de comandos: apuntes-c/cla.md
    - Memoria Dinámica: apuntes-c/memdin.md
    - Estructuras: apuntes-c/estructuras.md
